const StyleDictionary = require('style-dictionary');

// 커스텀 transform: Tokens Studio의 참조 형식({core.color.gray.50})을 Style Dictionary 형식으로 변환
StyleDictionary.registerTransform({
  name: 'name/cti/kebab',
  type: 'name',
  transformer: (token) => {
    return token.path.join('-');
  }
});

// TypeScript 타입 생성을 위한 커스텀 포맷
StyleDictionary.registerFormat({
  name: 'typescript/module-declarations',
  formatter: ({ dictionary }) => {
    const tokens = dictionary.allTokens;

    // 토큰을 그룹화
    const grouped = tokens.reduce((acc, token) => {
      const category = token.path[0];
      if (!acc[category]) acc[category] = [];
      acc[category].push(token);
      return acc;
    }, {});

    let output = `/**
 * Design Tokens
 * Auto-generated by Style Dictionary
 * DO NOT EDIT DIRECTLY
 */

export interface DesignTokens {\n`;

    Object.keys(grouped).forEach(category => {
      output += `  ${category}: {\n`;
      grouped[category].forEach(token => {
        const path = token.path.slice(1).join('.');
        output += `    '${path}': string;\n`;
      });
      output += `  };\n`;
    });

    output += `}\n\nexport const tokens: DesignTokens;\n`;
    return output;
  }
});

// 테마별 설정
const themes = ['light', 'dark'];

const getStyleDictionaryConfig = (theme) => ({
  source: [
    'tokens/core.json',
    `tokens/${theme}.json`
  ],
  platforms: {
    // CSS Variables 출력
    css: {
      transformGroup: 'css',
      buildPath: `src/css/`,
      files: [
        {
          destination: `${theme}.css`,
          format: 'css/variables',
          options: {
            selector: `[data-theme="${theme}"]`
          }
        }
      ]
    },
    // JavaScript/TypeScript 출력
    js: {
      transformGroup: 'js',
      buildPath: `src/js/`,
      files: [
        {
          destination: `${theme}.js`,
          format: 'javascript/module'
        },
        {
          destination: `${theme}.d.ts`,
          format: 'typescript/module-declarations'
        }
      ]
    },
    // JSON 출력 (디버깅용)
    json: {
      transformGroup: 'js',
      buildPath: `src/json/`,
      files: [
        {
          destination: `${theme}.json`,
          format: 'json/flat'
        }
      ]
    }
  }
});

// 빌드 실행
console.log('🎨 Building Design Tokens...\n');

themes.forEach(theme => {
  console.log(`\n📦 Building ${theme} theme...`);
  const sd = StyleDictionary.extend(getStyleDictionaryConfig(theme));
  sd.buildAllPlatforms();
});

console.log('\n✅ Design Tokens build completed!');
