import type { Metadata } from 'next';
import localFont from 'next/font/local';
import '@styles/globals.css';

import Layout from '@components/layouts/Layout';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
const pretendard = localFont({
  src: [
    {
      path: './font/subset-Pretendard-Regular.woff2',
      weight: '400',
    },

    {
      path: './font/subset-Pretendard-SemiBold.woff2',
      weight: '600',
    },
    {
      path: './font/subset-Pretendard-Bold.woff2',
      weight: '700',
    },
  ],
  variable: '--font-pretendard',
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko-KR" className={pretendard.className}>
      <body>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
