import type { Metadata } from 'next';
import localFont from 'next/font/local';

import '@styles/theme.scss';
import '@styles/globals.scss';

import Layout from '@components/layouts/Layout';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const pretendard = localFont({
  src: './font/PretendardVariable.woff2',
  display: 'swap',
  weight: '45 920',
  variable: '--pretendard',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko-KR">
      <body className={pretendard.className}>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
